(() => {
  "use strict";
  const $=id=>document.getElementById(id), mag=(x,y,z)=>Math.hypot(x,y,z), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const norm=v=>{const m=Math.hypot(...v)||1;return v.map(n=>n/m)},dot=(a,b)=>a.reduce((s,n,i)=>s+n*b[i],0);
  const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
  const deg=r=>r*180/Math.PI, fmt=(v,d=1)=>Number.isFinite(v)?v.toFixed(d):"--";
  const KEYS={config:"airswing-angle-config-v1",cal:"airswing-angle-cal-v1",sessions:"airswing-sessions-v1"};
  const load=(k,f)=>{try{return{...f,...JSON.parse(localStorage.getItem(k)||"{}")}}catch{return f}};
  const ui={};["liveDot","connectionText","sampleRate","contactAngle","angleResult","sessionHitCount","sessionStatus","swingAngle","stability","peakRot","peakHint","liveAngle","liveAngleHint","horizontalFace","horizontalFaceHint","swingDirection","swingDirectionHint","readyDelta","readyDeltaHint","contactState","startSession","endSession","exportJson","exportCsv","protocolNotice","targetAngle","targetAngleValue","tolerance","toleranceValue","gThreshold","gThresholdValue","rotThreshold","rotThresholdValue","autoThreshold","headRadius","headRadiusValue","calZero","calFront","calBack","calVertical","calTable","calReady","zeroTag","frontTag","backTag","verticalTag","tableTag","readyTag","clearCalibration","eventLog","sessionList","hitTable","emptyHits","landingStatus","undoLanding","accelerationChart","rotationChart","angleChart","analysisSelection","analysisReady","analysisAxial","analysisBackswing","analysisFollow","analysisReturn","analysisHeadSpeed","analysisPreAccel","analysisPeakTime","analysisDecel","analysisForward","analysisLateral","analysisFaceYaw","analysisSector","analysisFilter","analysisConfidence","analysisThreshold","coachTitle","coachAction","coachEvidence","coachReliability","summarySample","summaryInRate","summaryRepeatability","summaryReturnRate","summaryConfidence","summaryPattern","summaryRelation"].forEach(id=>ui[id]=$(id));
  const app={
    config:load(KEYS.config,{target:-10,tolerance:8,gThreshold:2.2,rotThreshold:3.5,autoThreshold:true,headRadiusCm:20}),
    calibration:load(KEYS.cal,{zero:null,front:null,back:null,vertical:null,table:null,ready:null}), sessions:[],
    active:null,selected:null,samples:[],chartSamples:[],sampleTimes:[],lastAt:0,chart:null,
    calibrationRun:null,stroke:null,preRoll:[],quietSince:0,lastStrokeAt:0,protocol:0,charts:[],quaternionMode:null,selectedHit:null,pendingReturns:[]
  };
  try{app.sessions=JSON.parse(localStorage.getItem(KEYS.sessions)||"[]")}catch{}
  const saveConfig=()=>localStorage.setItem(KEYS.config,JSON.stringify(app.config));
  const saveCal=()=>{localStorage.setItem(KEYS.cal,JSON.stringify(app.calibration));renderCalibration()};
  const saveSessions=()=>localStorage.setItem(KEYS.sessions,JSON.stringify(app.sessions.slice(0,30)));
  function log(text){const d=document.createElement("div");d.textContent=new Date().toLocaleTimeString()+"  "+text;ui.eventLog.prepend(d);while(ui.eventLog.children.length>18)ui.eventLog.lastChild.remove()}
  function angleLabel(v){if(!Number.isFinite(v))return"--";if(Math.abs(v)<1)return"接近竖直";return(v>0?"打开 ":"关闭 ")+Math.abs(Math.round(v))+"°"}
  function faceAxis(){const c=app.calibration.front;if(!c)return null;return norm(c.gravity.map(n=>-n))}
  function handleAxis(){const f=faceAxis(),c=app.calibration.vertical;if(!f||!c)return null;let h=norm(c.gravity.map(n=>-n));h=h.map((n,i)=>n-dot(h,f)*f[i]);return norm(h)}
  function faceAngle(s){const f=faceAxis();if(!f||!s.gravity)return null;return deg(Math.asin(clamp(dot(f,norm(s.gravity.map(n=>-n))),-1,1)))}
  function swingAngle(s){const h=handleAxis();if(!h||!s.gravity)return null;const v=cross([s.rotX,s.rotY,s.rotZ],h),up=norm(s.gravity.map(n=>-n));return deg(Math.atan2(dot(v,up),Math.hypot(...v.map((n,i)=>n-dot(v,up)*up[i]))))}
  function qConjugate(q){return[-q[0],-q[1],-q[2],q[3]]}
  function qRotate(q,v){const u=[q[0],q[1],q[2]],s=q[3],uv=cross(u,v),uuv=cross(u,uv);return v.map((n,i)=>n+2*s*uv[i]+2*uuv[i])}
  function worldVector(v,q,gravity){if(!q)return null;if(!app.quaternionMode&&gravity){const target=[0,0,-1],direct=qRotate(q,gravity),inverse=qRotate(qConjugate(q),gravity),error=a=>a.reduce((sum,n,i)=>sum+(n-target[i])**2,0);app.quaternionMode=error(direct)<=error(inverse)?"direct":"inverse"}return qRotate(app.quaternionMode==="inverse"?qConjugate(q):q,v)}
  function tableBasis(){const f=faceAxis(),h=handleAxis(),t=app.calibration.table,v=app.calibration.vertical;if(!f||!v?.quaternion)return null;const forwardRaw=t?.quaternion&&h?worldVector(h,t.quaternion,t.gravity):worldVector(f,v.quaternion,v.gravity);if(!forwardRaw)return null;const up=[0,0,1],flat=forwardRaw.map((n,i)=>n-dot(forwardRaw,up)*up[i]);if(Math.hypot(...flat)<.05)return null;const forward=norm(flat);return{up,forward,right:norm(cross(forward,up))}}
  function horizontalMetrics(s){const basis=tableBasis(),f=faceAxis(),h=handleAxis();if(!basis||!f||!h||!s.quaternion)return{faceYaw:null,swingYaw:null,forwardSpeed:null,lateralSpeed:null};const faceWorld=worldVector(f,s.quaternion,s.gravity),faceFlat=faceWorld.map((n,i)=>n-dot(faceWorld,basis.up)*basis.up[i]),omegaWorld=worldVector([s.rotX,s.rotY,s.rotZ],s.quaternion,s.gravity),headWorld=worldVector(h,s.quaternion,s.gravity),velocity=cross(omegaWorld,headWorld),velocityFlat=velocity.map((n,i)=>n-dot(velocity,basis.up)*basis.up[i]),faceHorizontal=Math.hypot(...faceFlat)>.05?norm(faceFlat):null,velocityHorizontal=Math.hypot(...velocityFlat)>.01?norm(velocityFlat):null,r=app.config.headRadiusCm/100;return{faceYaw:faceHorizontal?deg(Math.atan2(dot(faceHorizontal,basis.right),dot(faceHorizontal,basis.forward))):null,swingYaw:velocityHorizontal?deg(Math.atan2(dot(velocityHorizontal,basis.right),dot(velocityHorizontal,basis.forward))):null,forwardSpeed:dot(velocity,basis.forward)*r,lateralSpeed:dot(velocity,basis.right)*r}}
  function directionLabel(v){if(!Number.isFinite(v))return"需要重新校准竖直姿态";if(Math.abs(v)<2)return"接近正前方";return(v>0?"向右 ":"向左 ")+fmt(Math.abs(v))+"°"}
  function orientationDelta(s){const ready=app.calibration.ready?.quaternion;if(!ready||!s.quaternion)return null;return deg(2*Math.acos(clamp(Math.abs(dot(norm(ready),norm(s.quaternion))),-1,1)))}
  function angularPath(samples){let total=0;for(let i=1;i<samples.length;i++){const dt=Math.min(.05,(samples[i].t-samples[i-1].t)/1000);total+=(samples[i].rotNorm+samples[i-1].rotNorm)*.5*dt}return deg(total)}
  function axialRotation(samples){const h=handleAxis();if(!h)return null;let total=0;for(let i=1;i<samples.length;i++){const dt=Math.min(.05,(samples[i].t-samples[i-1].t)/1000),a=dot([samples[i-1].rotX,samples[i-1].rotY,samples[i-1].rotZ],h),b=dot([samples[i].rotX,samples[i].rotY,samples[i].rotZ],h);total+=(a+b)*.5*dt}return deg(total)}
  function linearSlope(samples,value){if(samples.length<3)return null;const t0=samples[0].t,points=samples.map(s=>[(s.t-t0)/1000,value(s)]),mt=points.reduce((a,p)=>a+p[0],0)/points.length,mv=points.reduce((a,p)=>a+p[1],0)/points.length,den=points.reduce((a,p)=>a+(p[0]-mt)**2,0);return den?points.reduce((a,p)=>a+(p[0]-mt)*(p[1]-mv),0)/den:null}
  function sectorLabel(v){if(!Number.isFinite(v))return"--";const a=((v+180)%360+360)%360-180,x=Math.abs(a);if(x<=22.5)return"正前";if(x<=67.5)return a>0?"右前":"左前";if(x<=112.5)return a>0?"正右":"正左";if(x<=157.5)return a>0?"右后":"左后";return"正后"}
  function average(values){const v=values.filter(Number.isFinite);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}
  function deviation(values){const v=values.filter(Number.isFinite),m=average(v);return v.length>1?Math.sqrt(v.reduce((a,n)=>a+(n-m)**2,0)/v.length):null}
  function correlation(pairs){const p=pairs.filter(([a,b])=>Number.isFinite(a)&&Number.isFinite(b));if(p.length<3)return null;const ax=average(p.map(x=>x[0])),ay=average(p.map(x=>x[1])),num=p.reduce((s,x)=>s+(x[0]-ax)*(x[1]-ay),0),dx=Math.sqrt(p.reduce((s,x)=>s+(x[0]-ax)**2,0)),dy=Math.sqrt(p.reduce((s,x)=>s+(x[1]-ay)**2,0));return dx&&dy?num/(dx*dy):null}
  function compactDirection(v){if(!Number.isFinite(v))return"--";if(Math.abs(v)<2)return"正前";return(v>0?"右 ":"左 ")+fmt(Math.abs(v))+"°"}
  function shotConclusion(h){
    if(!h)return{title:"完成校准并开始训练",action:"不标记落点也能看动作；标记后还能分析球为什么下网、出界或偏向一边。",evidence:"等待第一拍",reliability:"尚无数据"};
    const target=Number.isFinite(h.targetAngle)?h.targetAngle:app.config.target,tolerance=Number.isFinite(h.targetTolerance)?h.targetTolerance:app.config.tolerance,diff=h.angle-target,face=h.faceYaw,swing=h.swingYaw,landing=h.landing,confidence=Number.isFinite(h.confidence)?h.confidence:0,gap=Number.isFinite(face)&&Number.isFinite(swing)?Math.abs(face-swing):null,evidence="拍面 "+angleLabel(h.angle)+" · 拍子朝 "+compactDirection(face)+" · 手挥向 "+sectorLabel(swing),reliability=(landing?landing.label:"没标落点，只看动作")+" · 数据可信度 "+confidence+"%";
    if(confidence<45)return{title:"这拍数据不太可靠，先别急着改动作",action:"看看 AirPod 有没有松动，重新做一次静止校准，再打一拍。",evidence,reliability};
    if(!landing){
      if(Math.abs(diff)>tolerance)return{title:"击球时拍面比设定更"+(diff>0?"仰 ":"压 ")+Math.round(Math.abs(diff))+"°",action:"下一拍先把拍面往回调一点，其他动作尽量不变。",evidence,reliability};
      if(Number.isFinite(gap)&&gap>20)return{title:"拍子朝向和手挥方向差了 "+Math.round(gap)+"°",action:"下一拍让拍子朝向和挥拍终点尽量对着同一个方向。",evidence,reliability};
      if(Number.isFinite(h.peakSpeedOffsetMs)&&Math.abs(h.peakSpeedOffsetMs)>90)return{title:"发力最猛的时间"+(h.peakSpeedOffsetMs>0?"晚了 ":"早了 ")+Math.abs(Math.round(h.peakSpeedOffsetMs))+" ms",action:"尝试把最猛的发力点放到更接近触球的时候。",evidence,reliability};
      if(Number.isFinite(h.returnDelta)&&h.returnDelta>12)return{title:"打完后没有及时回到准备位置",action:"下一拍挥完不要停住，尽快把拍子收回准备位置。",evidence,reliability};
      return{title:"这拍动作整体比较接近当前设定",action:"因为没标落点，这里只评价动作，不猜球有没有上台或偏向哪边。",evidence,reliability};
    }
    if(landing.outcome==="net"){const cause=diff<-3&&h.swingAngle<-4?"拍面压得太低，而且手还在往下挥":diff<-3?"拍面压得太低":h.swingAngle<-4?"手明显往下挥":"球得到的向前上方力量不够";return{title:"这球下网，主要像是"+cause,action:diff<-3?"下一拍把拍面抬起一点。":"下一拍拍面先不变，手多往前上方送。",evidence,reliability}}
    if(landing.code==="out-long"){const cause=diff>3&&h.swingAngle>4?"拍面太仰，而且手往上送得多":diff>3?"拍面太仰":h.swingAngle>4?"手往上送得太多":"向前送得太猛或随挥太长";return{title:"这球打远了，主要像是"+cause,action:diff>3?"下一拍把拍面稍微压低一点。":"下一拍速度先保留，把向上或向前送的幅度缩小一点。",evidence,reliability}}
    if(landing.code==="out-left"||landing.code==="out-right"){const side=landing.code==="out-right"?1:-1,facePull=Number.isFinite(face)?side*face:0,swingPull=Number.isFinite(swing)?side*swing:0,cause=facePull>swingPull+5?"拍子本身朝偏了":"手挥偏了";return{title:"这球从"+(landing.code==="out-right"?"右边":"左边")+"出去，主要像是"+cause,action:cause==="拍子本身朝偏了"?"下一拍拍子朝中线回一点，挥拍节奏先不变。":"下一拍拍面先不变，手的终点往中线收一点。",evidence,reliability}}
    if(landing.outcome==="in"){const aligned=Number.isFinite(gap)&&gap<=15,onTarget=Math.abs(diff)<=tolerance;return{title:"这球上台了，落在"+landing.label+(aligned&&onTarget?"，可以拿它当参考":""),action:aligned&&onTarget?"试着重复刚才的拍面、挥拍方向和速度。":Math.abs(diff)>tolerance?"球虽然上台，但下一拍拍面可以往设定方向调一点。":"球已上台，下一拍让拍子朝向和手挥方向更一致。",evidence,reliability}}
    return{title:"已记录 "+landing.label,action:"继续积累相同类型击球，Session 关联需要至少 6 个已标记样本。",evidence,reliability}
  }
  function renderCoach(h){const c=shotConclusion(h);ui.coachTitle.textContent=c.title;ui.coachAction.textContent=c.action;ui.coachEvidence.textContent=c.evidence;ui.coachReliability.textContent=c.reliability}
  function motionPattern(hits,s,repeatability){
    if(hits.length<3)return"已经记录 "+hits.length+" 拍，再打 "+(3-hits.length)+" 拍就能开始总结动作。";
    const differences=hits.map(h=>h.angle-(Number.isFinite(h.targetAngle)?h.targetAngle:s.config?.target??app.config.target)).filter(Number.isFinite),meanDiff=average(differences),meanAbsDiff=average(differences.map(Math.abs)),gaps=hits.map(h=>Number.isFinite(h.faceYaw)&&Number.isFinite(h.swingYaw)?Math.abs(h.faceYaw-h.swingYaw):null),meanGap=average(gaps),timings=hits.map(h=>h.peakSpeedOffsetMs).filter(Number.isFinite),meanTiming=average(timings),returns=hits.filter(h=>Number.isFinite(h.returnDelta)),returnRate=returns.length?returns.filter(h=>h.returnDelta<=12).length/returns.length:null;
    if(Number.isFinite(meanAbsDiff)&&meanAbsDiff>app.config.tolerance)return"从动作看：拍面每拍平均差 "+fmt(meanAbsDiff)+"°，整体有点"+(meanDiff>=0?"太仰。":"太压。");
    if(Number.isFinite(meanGap)&&meanGap>20)return"从动作看：拍子朝向和手挥方向平均差 "+fmt(meanGap)+"°，左右方向没有对齐。";
    if(Number.isFinite(meanTiming)&&Math.abs(meanTiming)>80)return"从动作看：每拍发力最猛的时间平均"+(meanTiming>0?"晚了 ":"早了 ")+Math.abs(Math.round(meanTiming))+" ms。";
    if(Number.isFinite(returnRate)&&returnRate<.6)return"从动作看：打完后及时回位的只有 "+Math.round(returnRate*100)+"%。";
    if(Number.isFinite(repeatability)&&repeatability<70)return"从动作看：只有 "+repeatability+"% 的动作比较像，角度、方向或速度变化较大。";
    return"从动作看：拍面、方向和速度暂时没有特别突出的单一问题。"
  }
  function renderSummary(s){
    if(!s||!s.hits.length){ui.summarySample.textContent="还没有训练数据";ui.summaryInRate.textContent=ui.summaryRepeatability.textContent=ui.summaryReturnRate.textContent=ui.summaryConfidence.textContent="--";ui.summaryPattern.textContent="打满 3 拍后开始总结动作";ui.summaryRelation.textContent="标记落点后，才能分析什么动作容易把球打到哪里";return}
    const hits=s.hits,marked=hits.filter(h=>h.landing),inCount=marked.filter(h=>h.landing.outcome==="in").length,returned=hits.filter(h=>Number.isFinite(h.returnDelta)),angleSd=deviation(hits.map(h=>h.angle)),yawSd=deviation(hits.map(h=>h.swingYaw)),speeds=hits.map(h=>h.headSpeed).filter(Number.isFinite),speedMean=average(speeds),speedCv=speedMean?deviation(speeds)/speedMean:null,repeatability=hits.length>=3?Math.round(100-clamp((angleSd||0)*3+(yawSd||0)*.8+(speedCv||0)*30,0,100)):null;
    ui.summarySample.textContent=hits.length+" 次击球 · "+marked.length+" 次已标记 · "+(hits.length-marked.length)+" 次未标记";
    ui.summaryInRate.textContent=marked.length?Math.round(inCount/marked.length*100)+"%":"--";
    ui.summaryRepeatability.textContent=Number.isFinite(repeatability)?repeatability+"%":"--";
    ui.summaryReturnRate.textContent=returned.length?Math.round(returned.filter(h=>h.returnDelta<=12).length/returned.length*100)+"%":"--";
    const avgConfidence=average(hits.map(h=>h.confidence));ui.summaryConfidence.textContent=Number.isFinite(avgConfidence)?Math.round(avgConfidence)+"%":"--";
    const movement=motionPattern(hits,s,repeatability);
    if(marked.length>=3){const counts={};marked.forEach(h=>counts[h.landing.label]=(counts[h.landing.label]||0)+1);const main=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];ui.summaryPattern.textContent="最常见结果是“"+main[0]+"”（"+main[1]+"/"+marked.length+"）。"+movement}else ui.summaryPattern.textContent=movement;
    if(marked.length<6){ui.summaryRelation.textContent=marked.length?"已经标了 "+marked.length+" 球，再标 "+(6-marked.length)+" 球，就能看出什么动作容易打到哪里。":"还没有标落点，所以只总结动作，不猜球会落在哪里。";return}
    const lateral=h=>h.landing.lateral==="left"?-1:h.landing.lateral==="right"?1:h.landing.lateral==="center"?0:null,depth=h=>h.landing.code==="net"?-1:h.landing.code==="out-long"?1:h.landing.depth==="near"?-.5:h.landing.depth==="mid"?0:h.landing.depth==="far"?.5:null,relations=[{positive:"拍子越朝右，球越容易落到右边",negative:"拍子越朝右，球反而越容易落到左边",r:correlation(marked.map(h=>[h.faceYaw,lateral(h)]))},{positive:"手越往右挥，球越容易落到右边",negative:"手越往右挥，球反而越容易落到左边",r:correlation(marked.map(h=>[h.swingYaw,lateral(h)]))},{positive:"拍面越仰，球越容易打得深",negative:"拍面越仰，球反而越容易打得近",r:correlation(marked.map(h=>[h.angle,depth(h)]))},{positive:"手越往上挥，球越容易打得深",negative:"手越往上挥，球反而越容易打得近",r:correlation(marked.map(h=>[h.swingAngle,depth(h)]))}].filter(x=>Number.isFinite(x.r)).sort((a,b)=>Math.abs(b.r)-Math.abs(a.r));const best=relations[0];ui.summaryRelation.textContent=!best||Math.abs(best.r)<.25?"目前还看不出哪一个动作明显决定落点，多记录一些同类来球会更准。":(best.r>=0?best.positive:best.negative)+"（关联强度 "+fmt(Math.abs(best.r),2)+"，根据 "+marked.length+" 个已标记球得出）。"
  }
  function renderAnalysis(h){const fields=[ui.analysisReady,ui.analysisAxial,ui.analysisBackswing,ui.analysisFollow,ui.analysisReturn,ui.analysisHeadSpeed,ui.analysisPreAccel,ui.analysisPeakTime,ui.analysisDecel,ui.analysisForward,ui.analysisLateral,ui.analysisFaceYaw,ui.analysisSector,ui.analysisFilter,ui.analysisConfidence,ui.analysisThreshold];if(!h){ui.analysisSelection.textContent="选择一条击球记录";fields.forEach(n=>n.textContent="--");renderCoach(null);return}ui.analysisSelection.textContent="击球 #"+h.number+" · "+new Date(h.time).toLocaleTimeString();ui.analysisReady.textContent=fmt(h.readyDelta)+"°";ui.analysisAxial.textContent=Number.isFinite(h.axialRotation)?(h.axialRotation>=0?"内旋估计 ":"外旋估计 ")+fmt(Math.abs(h.axialRotation))+"°":"--";ui.analysisBackswing.textContent=fmt(h.backswingPath)+"°";ui.analysisFollow.textContent=fmt(h.followThroughPath)+"°";ui.analysisReturn.textContent=Number.isFinite(h.returnDelta)?(h.returnDelta<=12?"已回位 ":"偏离 ")+fmt(h.returnDelta)+"°":h.returnPending?"评估中":"--";ui.analysisHeadSpeed.textContent=Number.isFinite(h.headSpeed)?fmt(h.headSpeed,2)+" m/s":"--";ui.analysisPreAccel.textContent=Number.isFinite(h.preAcceleration)?fmt(h.preAcceleration,1)+" m/s²":"--";ui.analysisPeakTime.textContent=Number.isFinite(h.peakSpeedOffsetMs)?(h.peakSpeedOffsetMs>=0?"触球后 ":"触球前 ")+Math.abs(Math.round(h.peakSpeedOffsetMs))+" ms":"--";ui.analysisDecel.textContent=Number.isFinite(h.followDeceleration)?fmt(h.followDeceleration,1)+" m/s²":"--";ui.analysisForward.textContent=Number.isFinite(h.forwardSpeed)?(h.forwardSpeed>=0?"向前 ":"向后 ")+fmt(Math.abs(h.forwardSpeed),2)+" m/s":"--";ui.analysisLateral.textContent=Number.isFinite(h.lateralSpeed)?(h.lateralSpeed>=0?"向右 ":"向左 ")+fmt(Math.abs(h.lateralSpeed),2)+" m/s":"--";ui.analysisFaceYaw.textContent=Number.isFinite(h.faceYaw)?directionLabel(h.faceYaw):"--";ui.analysisSector.textContent=h.swingSector||"--";ui.analysisFilter.textContent=Number.isFinite(h.noiseFloorDeg)?"低于 "+fmt(h.noiseFloorDeg,1)+"°/s":"未校准";ui.analysisConfidence.textContent=Number.isFinite(h.confidence)?h.confidence+"%":"--";ui.analysisThreshold.textContent=Number.isFinite(h.gThreshold)?(h.autoThreshold?"自动":"手动")+" · "+fmt(h.gThreshold,1)+"g / "+fmt(h.rotThreshold,1)+"rad/s":"--";renderCoach(h)}
  function renderCalibration(){ui.zeroTag.classList.toggle("ready",!!app.calibration.zero);ui.frontTag.classList.toggle("ready",!!app.calibration.front);ui.backTag.classList.toggle("ready",!!app.calibration.back);ui.verticalTag.classList.toggle("ready",!!app.calibration.vertical?.quaternion);ui.tableTag.classList.toggle("ready",!!app.calibration.table?.quaternion);ui.readyTag.classList.toggle("ready",!!app.calibration.ready?.quaternion)}
  function renderConfig(){ui.targetAngle.value=app.config.target;ui.tolerance.value=app.config.tolerance;ui.gThreshold.value=app.config.gThreshold;ui.rotThreshold.value=app.config.rotThreshold;ui.autoThreshold.checked=!!app.config.autoThreshold;ui.headRadius.value=app.config.headRadiusCm;ui.targetAngleValue.textContent=angleLabel(app.config.target);ui.toleranceValue.textContent=app.config.tolerance;ui.gThresholdValue.textContent=Number(app.config.gThreshold).toFixed(1);ui.rotThresholdValue.textContent=Number(app.config.rotThreshold).toFixed(1);ui.headRadiusValue.textContent=app.config.headRadiusCm;ui.gThreshold.disabled=ui.rotThreshold.disabled=!!app.config.autoThreshold}
  function selectedSession(){const list=app.active?[app.active,...app.sessions]:app.sessions;return list.find(s=>s.id===app.selected)||app.active||app.sessions[0]}
  function renderSessions(){ui.sessionList.innerHTML="";const list=app.active?[app.active,...app.sessions]:app.sessions;if(!list.length){ui.sessionList.innerHTML='<div class="empty">还没有 Session</div>'}list.forEach(s=>{const b=document.createElement("button"),marked=s.hits.filter(h=>h.landing).length;b.className="session-item"+(app.selected===s.id?" active":"");b.innerHTML="<strong>"+(s.active?"训练中":"Session")+" · "+s.hits.length+" 次</strong><span>已标记 "+marked+" · "+new Date(s.startedAt).toLocaleString()+"</span>";b.onclick=()=>{app.selected=s.id;app.selectedHit=null;renderSessions()};ui.sessionList.appendChild(b)});const shown=selectedSession();renderHits(shown);renderLandingStatus(shown);renderSummary(shown)}
  function renderHits(s){ui.hitTable.innerHTML="";ui.emptyHits.style.display=s&&s.hits.length?"none":"block";if(!s){renderAnalysis(null);return}if(!s.hits.includes(app.selectedHit))app.selectedHit=s.hits.at(-1)||null;s.hits.forEach(h=>{const tr=document.createElement("tr"),target=Number.isFinite(h.targetAngle)?h.targetAngle:s.config?.target??app.config.target,diff=h.angle-target;tr.className="hit-row"+(app.selectedHit===h?" active":"");tr.innerHTML="<td>#"+h.number+"</td><td>"+(h.landing?.label||"未标记")+"</td><td>"+new Date(h.time).toLocaleTimeString()+"</td><td>"+(Number.isFinite(h.confidence)?h.confidence+"%":"--")+"</td><td>"+fmt(h.headSpeed,2)+" m/s</td><td>"+angleLabel(h.angle)+"</td><td>"+(Number.isFinite(h.faceYaw)?directionLabel(h.faceYaw):"--")+"</td><td>"+(Number.isFinite(h.swingYaw)?directionLabel(h.swingYaw):"--")+"</td><td>"+fmt(h.readyDelta)+"°</td><td>"+(diff>=0?"+":"")+fmt(diff)+"°</td><td>"+fmt(h.swingAngle)+"°</td><td>"+fmt(h.stability)+"°</td><td>"+fmt(h.peakG,2)+"</td><td>"+Math.round(h.peakRotDeg)+"°/s</td>";tr.onclick=()=>{app.selectedHit=h;renderHits(s)};ui.hitTable.appendChild(tr)});renderAnalysis(app.selectedHit)}
  function renderLandingStatus(s){if(!s||!s.hits.length){ui.landingStatus.textContent="等待 Session 击球";return}const pending=[...s.hits].reverse().find(h=>!h.landing);ui.landingStatus.textContent=pending?"待标记：击球 #"+pending.number:"本 Session 已全部标记"}
  const landingLabels={"far-left":"左远","far-center":"中远","far-right":"右远","mid-left":"左中","mid-center":"中间","mid-right":"右中","near-left":"左近","near-center":"中近","near-right":"右近",net:"下网","out-long":"远出界","out-left":"左出界","out-right":"右出界"};
  function landingData(code){if(code==="net")return{outcome:"net",depth:"short",lateral:"center"};if(code==="out-long")return{outcome:"out",depth:"long",lateral:"center"};if(code==="out-left")return{outcome:"out",depth:"unknown",lateral:"left"};if(code==="out-right")return{outcome:"out",depth:"unknown",lateral:"right"};const [depth,lateral]=code.split("-");return{outcome:"in",depth,lateral}}
  function markLanding(code){const s=selectedSession();if(!s||!s.hits.length){log("还没有可标记的击球");return}const hit=[...s.hits].reverse().find(h=>!h.landing);if(!hit){log("当前 Session 已全部标记");return}hit.landing={code,label:landingLabels[code],...landingData(code),markedAt:Date.now()};if(!s.active)saveSessions();log("击球 #"+hit.number+" 标记为 "+hit.landing.label);renderSessions()}
  function undoLanding(){const s=selectedSession();if(!s)return;const hit=[...s.hits].reverse().find(h=>h.landing);if(!hit){log("没有可撤销的落点标记");return}const label=hit.landing.label;delete hit.landing;if(!s.active)saveSessions();log("已撤销击球 #"+hit.number+" 的 "+label);renderSessions()}
  function startSession(){if(app.active)return;app.active={id:"s-"+Date.now(),startedAt:Date.now(),endedAt:null,active:true,hits:[],sampleCount:0,maxG:0,config:{...app.config}};app.samples=[];app.selected=app.active.id;app.selectedHit=null;ui.startSession.disabled=true;ui.endSession.disabled=false;ui.sessionStatus.textContent="训练进行中";ui.sessionHitCount.textContent="0";log("Session 已开始");renderSessions()}
  function endSession(){if(!app.active)return;app.active.active=false;app.active.endedAt=Date.now();app.sessions.unshift(app.active);app.sessions=app.sessions.slice(0,30);app.selected=app.active.id;app.active=null;saveSessions();ui.startSession.disabled=false;ui.endSession.disabled=true;ui.sessionStatus.textContent="已保存，可在下方回看";log("Session 已结束并保存");renderSessions()}
  function strokeConfidence(st,peak,contact){const early=st.filter(s=>s.t<contact.t-100),baseline=early.length?early.reduce((a,s)=>a+s.totalG,0)/early.length:1,g=clamp((peak.totalG/app.config.gThreshold-1)/1.2,0,1),r=clamp((peak.rotNorm/app.config.rotThreshold-1)/1.5,0,1),prominence=clamp((peak.totalG-baseline)/Math.max(.3,app.config.gThreshold-1),0,1),calibration=["zero","front","vertical","table","ready"].filter(k=>app.calibration[k]).length/5,duration=Math.max(1,st.at(-1).t-st[0].t),rate=clamp(st.length/(duration/20),0,1);return Math.round(100*(.24*g+.24*r+.2*prominence+.22*calibration+.1*rate))}
  function updatePendingReturns(s){let finished=false;app.pendingReturns=app.pendingReturns.filter(p=>{if(s.t>=p.start&&s.t<=p.expires){const d=orientationDelta(s);if(Number.isFinite(d))p.hit.returnDelta=Number.isFinite(p.hit.returnDelta)?Math.min(p.hit.returnDelta,d):d}if(s.t<p.expires)return true;p.hit.returnPending=false;finished=true;return false});if(finished){if(!app.active)saveSessions();renderSessions()}}
  function feedback(h){ui.contactAngle.textContent=fmt(h.angle);ui.swingAngle.textContent=fmt(h.swingAngle);ui.stability.textContent=fmt(h.stability);ui.horizontalFace.textContent=fmt(h.faceYaw);ui.horizontalFaceHint.textContent=directionLabel(h.faceYaw);ui.swingDirection.textContent=fmt(h.swingYaw);ui.swingDirectionHint.textContent=directionLabel(h.swingYaw)+" · 旋转分量";ui.readyDelta.textContent=fmt(h.readyDelta);ui.readyDeltaHint.textContent=Number.isFinite(h.readyDelta)?"相对个人准备姿态":"需要准备姿态校准";ui.peakRot.textContent=Math.round(h.peakRotDeg);ui.peakHint.textContent="峰值 "+fmt(h.peakG,2)+" g";ui.contactState.textContent="数据 "+h.confidence+"%";const d=h.angle-app.config.target,a=Math.abs(d),cls=a<=app.config.tolerance?"good":a<=app.config.tolerance*2?"warn":"bad";ui.angleResult.className="hint "+cls;ui.angleResult.textContent=angleLabel(h.angle)+" · "+(a<.5?"刚好达到设定":(d>0?"比设定更仰 ":"比设定更压 ")+fmt(a)+"°");document.body.classList.remove("flash");void document.body.offsetWidth;document.body.classList.add("flash")}
  function finishStroke(){
    const st=app.stroke;app.stroke=null;app.quietSince=0;if(!st||st.length<5)return;
    let peak=st[0],score=-1;
    st.forEach(s=>{const q=s.totalG/app.config.gThreshold+s.rotNorm/app.config.rotThreshold;if(q>score){score=q;peak=s}});
    app.lastStrokeAt=st.at(-1).t;
    if(peak.totalG<app.config.gThreshold||peak.rotNorm<app.config.rotThreshold)return;
    const wanted=peak.t-40,contact=st.reduce((best,s)=>s.t<=peak.t&&Math.abs(s.t-wanted)<Math.abs(best.t-wanted)?s:best,peak),angle=faceAngle(contact);
    if(angle===null){log("检测到击球，但旧版网桥没有重力数据");return}
    const horizontal=horizontalMetrics(contact),pre=st.filter(s=>s.t>=contact.t-500&&s.t<=contact.t),post=st.filter(s=>s.t>=contact.t),angleSamples=st.filter(s=>s.t>=contact.t-140&&s.t<=contact.t).map(faceAngle).filter(Number.isFinite),mean=angleSamples.reduce((a,b)=>a+b,0)/(angleSamples.length||1),stability=Math.sqrt(angleSamples.reduce((a,b)=>a+(b-mean)**2,0)/(angleSamples.length||1)),fastest=st.reduce((a,s)=>s.rotNorm>a.rotNorm?s:a,st[0]),radius=app.config.headRadiusCm/100,accelWindow=pre.filter(s=>s.t>=contact.t-180),decelWindow=post.filter(s=>s.t<=contact.t+350),decelSlope=linearSlope(decelWindow,s=>s.rotNorm*radius),noiseFloor=Math.max(.08,(app.calibration.zero?.rotNoise||0)*3);
    const h={number:app.active?app.active.hits.length+1:0,time:peak.wallTime,angle,targetAngle:app.config.target,targetTolerance:app.config.tolerance,faceYaw:horizontal.faceYaw,swingYaw:horizontal.swingYaw,swingSector:sectorLabel(horizontal.swingYaw),forwardSpeed:horizontal.forwardSpeed,lateralSpeed:horizontal.lateralSpeed,readyDelta:orientationDelta(contact),returnDelta:null,returnPending:true,axialRotation:axialRotation(pre.filter(s=>s.t>=contact.t-300)),backswingPath:angularPath(pre),followThroughPath:angularPath(post),headSpeed:fastest.rotNorm*radius,preAcceleration:linearSlope(accelWindow,s=>s.rotNorm*radius),peakSpeedOffsetMs:fastest.t-contact.t,followDeceleration:Number.isFinite(decelSlope)?Math.max(0,-decelSlope):null,swingAngle:swingAngle(contact),stability,peakG:Math.max(...st.map(s=>s.totalG)),peakRotDeg:deg(fastest.rotNorm),noiseFloorDeg:deg(noiseFloor),confidence:strokeConfidence(st,peak,contact),gThreshold:app.config.gThreshold,rotThreshold:app.config.rotThreshold,autoThreshold:app.config.autoThreshold,headRadiusCm:app.config.headRadiusCm,contactOffsetMs:-40};
    feedback(h);renderAnalysis(h);app.pendingReturns.push({hit:h,start:contact.t+350,expires:contact.t+2000});
    if(app.active){app.active.hits.push(h);app.selectedHit=h;ui.sessionHitCount.textContent=app.active.hits.length;renderSessions();log("记录击球 #"+h.number+"，置信度 "+h.confidence+"%")}else log("检测到击球；开始 Session 后才会保存")
  }
  function detect(s){app.preRoll.push(s);while(app.preRoll.length>40)app.preRoll.shift();if(!app.stroke){if(s.motionRot>Math.max(1.2,app.config.rotThreshold*.5)&&s.t-app.lastStrokeAt>180)app.stroke=app.preRoll.slice();return}app.stroke.push(s);if(s.motionRot<Math.max(.5,app.config.rotThreshold*.2)){if(!app.quietSince)app.quietSince=s.t;if(s.t-app.quietSince>220)finishStroke()}else app.quietSince=0;if(app.stroke&&s.t-app.stroke[0].t>2400)finishStroke()}
  function ingest(values,source="ipad"){const [ax,ay,az,rx,ry,rz,gx,gy,gz,qx,qy,qz,qw]=values.map(Number),now=performance.now();if(![ax,ay,az,rx,ry,rz].every(Number.isFinite))return;const rawAcc=[ax,ay,az],rawRot=[rx,ry,rz],accBias=app.calibration.zero?.accBias||[0,0,0],rotBias=app.calibration.zero?.rotBias||[0,0,0],acc=rawAcc.map((n,i)=>n-(accBias[i]||0)),rot=rawRot.map((n,i)=>n-(rotBias[i]||0)),rotNorm=mag(...rot),noiseFloor=Math.max(.08,(app.calibration.zero?.rotNoise||0)*3);const s={t:now,wallTime:Date.now(),source,rawAcc,rawRot,accX:acc[0],accY:acc[1],accZ:acc[2],rotX:rot[0],rotY:rot[1],rotZ:rot[2],totalG:mag(...acc),rotNorm,motionRot:Math.max(0,rotNorm-noiseFloor),gravity:[gx,gy,gz].every(Number.isFinite)?[gx,gy,gz]:null,quaternion:[qx,qy,qz,qw].every(Number.isFinite)?[qx,qy,qz,qw]:null};app.lastAt=now;app.protocol=s.gravity?2:1;ui.protocolNotice.textContent=s.gravity?"13 项数据已连接，拍面角可用":"只收到 "+values.length+" 项数据：当前运行的是旧 Swift 项目";ui.protocolNotice.className=s.gravity?"protocol good":"protocol";ui.liveDot.classList.add("live");ui.connectionText.textContent="接收中";app.sampleTimes.push(now);while(app.sampleTimes[0]<now-1000)app.sampleTimes.shift();ui.sampleRate.textContent=app.sampleTimes.length+" Hz";const a=faceAngle(s);ui.liveAngle.textContent=fmt(a);ui.liveAngleHint.textContent=a===null?"等待重力数据":angleLabel(a);ui.peakHint.textContent="当前 "+fmt(s.totalG,2)+" g";app.chartSamples.push(s);while(app.chartSamples[0]?.t<now-3000)app.chartSamples.shift();if(app.active){app.samples.push(s);app.active.sampleCount++;app.active.maxG=Math.max(app.active.maxG,s.totalG)}if(app.calibrationRun)app.calibrationRun.samples.push(s);detect(s);updatePendingReturns(s);updateChart()}
  window.onSensorData=(...v)=>ingest(v);
  function calibrate(kind,label){if(app.calibrationRun)return;if(kind==="table"&&(!faceAxis()||!handleAxis())){log("请先完成正面和竖直校准");return}const duration=kind==="zero"?3000:2000,run={kind,label,samples:[]};app.calibrationRun=run;log(label+"校准开始，保持静止 "+duration/1000+" 秒");setTimeout(()=>{if(app.calibrationRun!==run)return;app.calibrationRun=null;const valid=run.samples.filter(s=>s.gravity&&s.quaternion);if(valid.length<(kind==="zero"?45:30)){log("校准失败：没有足够的姿态数据");return}const gravity=[0,1,2].map(i=>valid.reduce((a,s)=>a+s.gravity[i],0)/valid.length),reference=valid[0].quaternion,qsum=[0,0,0,0];valid.forEach(s=>{const sign=dot(s.quaternion,reference)<0?-1:1;s.quaternion.forEach((n,i)=>qsum[i]+=n*sign)});const quaternion=norm(qsum),base={gravity,quaternion,samples:valid.length,at:Date.now()};if(kind==="zero"){const rotBias=[0,1,2].map(i=>valid.reduce((a,s)=>a+s.rawRot[i],0)/valid.length),linear=valid.map(s=>s.rawAcc.map((n,i)=>n-s.gravity[i])),accBias=[0,1,2].map(i=>linear.reduce((a,v)=>a+v[i],0)/linear.length),rotNoise=Math.sqrt(valid.reduce((a,s)=>a+s.rawRot.reduce((q,n,i)=>q+(n-rotBias[i])**2,0),0)/valid.length),accNoise=Math.sqrt(linear.reduce((a,v)=>a+v.reduce((q,n,i)=>q+(n-accBias[i])**2,0),0)/linear.length);app.calibration.zero={...base,rotBias,accBias,rotNoise,accNoise};if(app.config.autoThreshold){app.config.gThreshold=Math.round(clamp(1.8+accNoise*10,1.8,3.2)*10)/10;app.config.rotThreshold=Math.round(clamp(2.5+rotNoise*10,2.5,6)*10)/10;saveConfig();renderConfig()}log(label+"完成，陀螺噪声 "+fmt(deg(rotNoise),2)+"°/s，加速度噪声 "+fmt(accNoise,3)+" g，阈值 "+fmt(app.config.gThreshold,1)+"g / "+fmt(app.config.rotThreshold,1)+"rad/s")}else{app.calibration[kind]=base;if(kind==="vertical"||kind==="table")app.quaternionMode=null;if(kind==="back"&&app.calibration.front){const a=deg(Math.acos(clamp(dot(norm(app.calibration.front.gravity),norm(gravity)),-1,1)));log(label+"完成，正反面夹角 "+fmt(a)+"°")}else log(label+"校准完成")}saveCal()},duration)}
  function drawSeries(chart){const c=chart.canvas,ctx=c.getContext("2d"),dpr=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;if(!w||!h)return;if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const data=app.chartSamples,values=data.map(chart.value).filter(Number.isFinite),pad={l:40,r:10,t:10,b:22},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b;let min=chart.symmetric?-Math.max(chart.floor,...values.map(Math.abs)):0,max=chart.symmetric?Math.max(chart.floor,...values.map(Math.abs)):Math.max(chart.floor,...values);if(chart.symmetric)max=-min;ctx.strokeStyle="#202a36";ctx.fillStyle="#96a2b2";ctx.font="11px system-ui";for(let i=0;i<=4;i++){const y=pad.t+ph*i/4,v=max-(max-min)*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText(fmt(v,0),4,y+4)}if(values.length>1){ctx.strokeStyle=chart.color;ctx.lineWidth=2;ctx.beginPath();values.forEach((v,i)=>{const x=pad.l+pw*i/(values.length-1),y=pad.t+ph*(max-v)/(max-min);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}ctx.fillStyle="#96a2b2";ctx.fillText("-3s",pad.l,h-4);ctx.fillText("现在",w-pad.r-24,h-4)}
  function drawCharts(){app.charts.forEach(drawSeries)}
  function initChart(){app.charts=[{canvas:ui.accelerationChart,value:s=>s.totalG,color:"#43df8a",floor:4,symmetric:false},{canvas:ui.rotationChart,value:s=>deg(s.rotNorm),color:"#67a8ff",floor:720,symmetric:false},{canvas:ui.angleChart,value:s=>faceAngle(s),color:"#f4c95d",floor:45,symmetric:true}];window.addEventListener("resize",drawCharts);drawCharts()}
  function updateChart(){drawCharts()}
  function download(type){const s=app.active||app.sessions.find(x=>x.id===app.selected)||app.sessions[0];if(!s){log("没有可导出的 Session");return}let body,name;if(type==="json"){body=JSON.stringify({...s,calibration:app.calibration,rawSamples:app.active&&s.id===app.active.id?app.samples:undefined},null,2);name="airswing-"+s.id+".json"}else{const head="number,landingCode,landingLabel,outcome,depth,lateral,time,confidencePct,faceAngleDeg,faceYawDeg,swingYawDeg,swingSector,readyDeltaDeg,returnDeltaDeg,axialRotationDeg,backswingPathDeg,followThroughPathDeg,headSpeedMps,preAccelerationMps2,peakSpeedOffsetMs,followDecelerationMps2,forwardSpeedMps,lateralSpeedMps,targetDifferenceDeg,swingAngleDeg,stabilityDeg,peakG,peakRotationDegPerSec,noiseFloorDegPerSec,gThreshold,rotThreshold,headRadiusCm";body=[head,...s.hits.map(h=>[h.number,h.landing?.code||"",h.landing?.label||"",h.landing?.outcome||"",h.landing?.depth||"",h.landing?.lateral||"",new Date(h.time).toISOString(),h.confidence,h.angle,h.faceYaw,h.swingYaw,h.swingSector,h.readyDelta,h.returnDelta,h.axialRotation,h.backswingPath,h.followThroughPath,h.headSpeed,h.preAcceleration,h.peakSpeedOffsetMs,h.followDeceleration,h.forwardSpeed,h.lateralSpeed,h.angle-s.config.target,h.swingAngle,h.stability,h.peakG,h.peakRotDeg,h.noiseFloorDeg,h.gThreshold,h.rotThreshold,h.headRadiusCm].join(","))].join("\n");name="airswing-"+s.id+".csv"}const u=URL.createObjectURL(new Blob([body],{type:type==="json"?"application/json":"text/csv"})),a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
  ui.startSession.onclick=startSession;ui.endSession.onclick=endSession;ui.exportJson.onclick=()=>download("json");ui.exportCsv.onclick=()=>download("csv");ui.undoLanding.onclick=undoLanding;document.querySelectorAll("[data-landing]").forEach(button=>button.onclick=()=>markLanding(button.dataset.landing));ui.calZero.onclick=()=>calibrate("zero","静止零偏");ui.calFront.onclick=()=>calibrate("front","正手面");ui.calBack.onclick=()=>calibrate("back","反面");ui.calVertical.onclick=()=>calibrate("vertical","竖直姿态");ui.calTable.onclick=()=>calibrate("table","球桌方向");ui.calReady.onclick=()=>calibrate("ready","准备姿态");ui.clearCalibration.onclick=()=>{app.calibration={zero:null,front:null,back:null,vertical:null,table:null,ready:null};app.quaternionMode=null;saveCal();log("校准已清除")};
  [["targetAngle","target"],["tolerance","tolerance"],["gThreshold","gThreshold"],["rotThreshold","rotThreshold"]].forEach(([id,key])=>ui[id].oninput=()=>{app.config[key]=Number(ui[id].value);saveConfig();renderConfig()});
  ui.autoThreshold.onchange=()=>{app.config.autoThreshold=ui.autoThreshold.checked;const z=app.calibration.zero;if(z&&app.config.autoThreshold){app.config.gThreshold=Math.round(clamp(1.8+z.accNoise*10,1.8,3.2)*10)/10;app.config.rotThreshold=Math.round(clamp(2.5+z.rotNoise*10,2.5,6)*10)/10}saveConfig();renderConfig()};
  ui.headRadius.oninput=()=>{app.config.headRadiusCm=Number(ui.headRadius.value);saveConfig();renderConfig()};
  setInterval(()=>{if(app.lastAt&&performance.now()-app.lastAt>1300){ui.liveDot.classList.remove("live");ui.connectionText.textContent="等待 iPad 数据";ui.sampleRate.textContent="0 Hz"}},500);
  renderConfig();renderCalibration();renderSessions();initChart();log("角度训练版已就绪");
})();
