(() => {
  "use strict";
  const $=id=>document.getElementById(id), mag=(x,y,z)=>Math.hypot(x,y,z), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const norm=v=>{const m=Math.hypot(...v)||1;return v.map(n=>n/m)},dot=(a,b)=>a.reduce((s,n,i)=>s+n*b[i],0);
  const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
  const deg=r=>r*180/Math.PI, fmt=(v,d=1)=>Number.isFinite(v)?v.toFixed(d):"--";
  const KEYS={config:"airswing-angle-config-v1",cal:"airswing-angle-cal-v1",sessions:"airswing-sessions-v1"};
  const load=(k,f)=>{try{return{...f,...JSON.parse(localStorage.getItem(k)||"{}")}}catch{return f}};
  const ui={};["liveDot","connectionText","sampleRate","contactAngle","angleResult","sessionHitCount","sessionStatus","swingAngle","stability","peakRot","peakHint","liveAngle","liveAngleHint","contactState","startSession","endSession","exportJson","exportCsv","protocolNotice","targetAngle","targetAngleValue","tolerance","toleranceValue","gThreshold","gThresholdValue","rotThreshold","rotThresholdValue","calFront","calBack","calVertical","frontTag","backTag","verticalTag","clearCalibration","eventLog","sessionList","hitTable","emptyHits","motionChart"].forEach(id=>ui[id]=$(id));
  const app={
    config:load(KEYS.config,{target:-10,tolerance:8,gThreshold:2.2,rotThreshold:3.5}),
    calibration:load(KEYS.cal,{front:null,back:null,vertical:null}), sessions:[],
    active:null,selected:null,samples:[],chartSamples:[],sampleTimes:[],lastAt:0,chart:null,
    calibrationRun:null,stroke:null,preRoll:[],quietSince:0,lastStrokeAt:0,protocol:0
  };
  try{app.sessions=JSON.parse(localStorage.getItem(KEYS.sessions)||"[]")}catch{}
  const saveConfig=()=>localStorage.setItem(KEYS.config,JSON.stringify(app.config));
  const saveCal=()=>{localStorage.setItem(KEYS.cal,JSON.stringify(app.calibration));renderCalibration()};
  const saveSessions=()=>localStorage.setItem(KEYS.sessions,JSON.stringify(app.sessions.slice(0,30)));
  function log(text){const d=document.createElement("div");d.textContent=new Date().toLocaleTimeString()+"  "+text;ui.eventLog.prepend(d);while(ui.eventLog.children.length>18)ui.eventLog.lastChild.remove()}
  function angleLabel(v){if(!Number.isFinite(v))return"--";if(Math.abs(v)<1)return"接近竖直";return(v>0?"打开 ":"关闭 ")+Math.abs(Math.round(v))+"°"}
  function faceAxis(){const c=app.calibration.front;if(!c)return null;return norm(c.gravity.map(n=>-n))}
  function handleAxis(){const f=faceAxis(),c=app.calibration.vertical;if(!f||!c)return null;let h=norm(c.gravity.map(n=>-n));h=h.map((n,i)=>n-dot(h,f)*f[i]);return norm(h)}
  function faceAngle(s){const f=faceAxis();if(!f||!s.gravity)return null;return deg(Math.asin(clamp(dot(f,norm(s.gravity.map(n=>-n))),-1,1)))}
  function swingAngle(s){const h=handleAxis();if(!h||!s.gravity)return null;const v=cross([s.rotX,s.rotY,s.rotZ],h),up=norm(s.gravity.map(n=>-n));return deg(Math.atan2(dot(v,up),Math.hypot(...v.map((n,i)=>n-dot(v,up)*up[i]))))}
  function renderCalibration(){ui.frontTag.classList.toggle("ready",!!app.calibration.front);ui.backTag.classList.toggle("ready",!!app.calibration.back);ui.verticalTag.classList.toggle("ready",!!app.calibration.vertical)}
  function renderConfig(){ui.targetAngle.value=app.config.target;ui.tolerance.value=app.config.tolerance;ui.gThreshold.value=app.config.gThreshold;ui.rotThreshold.value=app.config.rotThreshold;ui.targetAngleValue.textContent=angleLabel(app.config.target);ui.toleranceValue.textContent=app.config.tolerance;ui.gThresholdValue.textContent=Number(app.config.gThreshold).toFixed(1);ui.rotThresholdValue.textContent=Number(app.config.rotThreshold).toFixed(1)}
  function renderSessions(){ui.sessionList.innerHTML="";const list=app.active?[app.active,...app.sessions]:app.sessions;if(!list.length){ui.sessionList.innerHTML='<div class="empty">还没有 Session</div>'}list.forEach(s=>{const b=document.createElement("button");b.className="session-item"+(app.selected===s.id?" active":"");b.innerHTML="<strong>"+(s.active?"训练中":"Session")+" · "+s.hits.length+" 次</strong><span>"+new Date(s.startedAt).toLocaleString()+"</span>";b.onclick=()=>{app.selected=s.id;renderSessions();renderHits(s)};ui.sessionList.appendChild(b)});const shown=list.find(s=>s.id===app.selected)||app.active||app.sessions[0];renderHits(shown)}
  function renderHits(s){ui.hitTable.innerHTML="";ui.emptyHits.style.display=s&&s.hits.length?"none":"block";if(!s)return;s.hits.forEach(h=>{const tr=document.createElement("tr"),diff=h.angle-app.config.target;tr.innerHTML="<td>#"+h.number+"</td><td>"+new Date(h.time).toLocaleTimeString()+"</td><td>"+angleLabel(h.angle)+"</td><td>"+(diff>=0?"+":"")+fmt(diff)+"°</td><td>"+fmt(h.swingAngle)+"°</td><td>"+fmt(h.stability)+"°</td><td>"+fmt(h.peakG,2)+"</td><td>"+Math.round(h.peakRotDeg)+"°/s</td>";ui.hitTable.appendChild(tr)})}
  function startSession(){if(app.active)return;app.active={id:"s-"+Date.now(),startedAt:Date.now(),endedAt:null,active:true,hits:[],sampleCount:0,maxG:0,config:{...app.config}};app.samples=[];app.selected=app.active.id;ui.startSession.disabled=true;ui.endSession.disabled=false;ui.sessionStatus.textContent="训练进行中";ui.sessionHitCount.textContent="0";log("Session 已开始");renderSessions()}
  function endSession(){if(!app.active)return;app.active.active=false;app.active.endedAt=Date.now();app.sessions.unshift(app.active);app.sessions=app.sessions.slice(0,30);app.selected=app.active.id;app.active=null;saveSessions();ui.startSession.disabled=false;ui.endSession.disabled=true;ui.sessionStatus.textContent="已保存，可在下方回看";log("Session 已结束并保存");renderSessions()}
  function feedback(h){ui.contactAngle.textContent=fmt(h.angle);ui.swingAngle.textContent=fmt(h.swingAngle);ui.stability.textContent=fmt(h.stability);ui.peakRot.textContent=Math.round(h.peakRotDeg);ui.peakHint.textContent="峰值 "+fmt(h.peakG,2)+" g";ui.contactState.textContent="已记录";const d=h.angle-app.config.target,a=Math.abs(d),cls=a<=app.config.tolerance?"good":a<=app.config.tolerance*2?"warn":"bad";ui.angleResult.className="hint "+cls;ui.angleResult.textContent=angleLabel(h.angle)+" · "+(a<.5?"达到目标":(d>0?"比目标更打开 ":"比目标更关闭 ")+fmt(a)+"°");document.body.classList.remove("flash");void document.body.offsetWidth;document.body.classList.add("flash")}
  function finishStroke(){const st=app.stroke;app.stroke=null;app.quietSince=0;if(!st||st.length<5)return;let peak=st[0],score=-1;st.forEach(s=>{const q=s.totalG/app.config.gThreshold+s.rotNorm/app.config.rotThreshold;if(q>score){score=q;peak=s}});app.lastStrokeAt=st.at(-1).t;if(peak.totalG<app.config.gThreshold||peak.rotNorm<app.config.rotThreshold)return;const wanted=peak.t-40,contact=st.reduce((best,s)=>s.t<=peak.t&&Math.abs(s.t-wanted)<Math.abs(best.t-wanted)?s:best,peak);const angle=faceAngle(contact);if(angle===null){log("检测到击球，但旧版网桥没有重力数据");return}const pre=st.filter(s=>s.t>=contact.t-140&&s.t<=contact.t).map(faceAngle).filter(Number.isFinite),mean=pre.reduce((a,b)=>a+b,0)/(pre.length||1),stability=Math.sqrt(pre.reduce((a,b)=>a+(b-mean)**2,0)/(pre.length||1));const h={number:app.active?app.active.hits.length+1:0,time:peak.wallTime,angle,swingAngle:swingAngle(contact),stability,peakG:Math.max(...st.map(s=>s.totalG)),peakRotDeg:deg(Math.max(...st.map(s=>s.rotNorm))),contactOffsetMs:-40};feedback(h);if(app.active){app.active.hits.push(h);ui.sessionHitCount.textContent=app.active.hits.length;renderSessions();log("记录击球 #"+h.number+"，"+angleLabel(angle))}else log("检测到击球；开始 Session 后才会保存")}
  function detect(s){app.preRoll.push(s);while(app.preRoll.length>8)app.preRoll.shift();if(!app.stroke){if(s.rotNorm>1.8&&s.t-app.lastStrokeAt>180)app.stroke=app.preRoll.slice();return}app.stroke.push(s);if(s.rotNorm<.8){if(!app.quietSince)app.quietSince=s.t;if(s.t-app.quietSince>120)finishStroke()}else app.quietSince=0;if(app.stroke&&s.t-app.stroke[0].t>1500)finishStroke()}
  function ingest(values,source="ipad"){const [ax,ay,az,rx,ry,rz,gx,gy,gz,qx,qy,qz,qw]=values.map(Number),now=performance.now();if(![ax,ay,az,rx,ry,rz].every(Number.isFinite))return;const s={t:now,wallTime:Date.now(),source,accX:ax,accY:ay,accZ:az,rotX:rx,rotY:ry,rotZ:rz,totalG:mag(ax,ay,az),rotNorm:mag(rx,ry,rz),gravity:[gx,gy,gz].every(Number.isFinite)?[gx,gy,gz]:null,quaternion:[qx,qy,qz,qw].every(Number.isFinite)?[qx,qy,qz,qw]:null};app.lastAt=now;app.protocol=s.gravity?2:1;ui.protocolNotice.textContent=s.gravity?"新版网桥：拍面角数据可用":"旧版网桥：请下载更新后的 Swift 项目";ui.protocolNotice.className=s.gravity?"protocol good":"protocol";ui.liveDot.classList.add("live");ui.connectionText.textContent="接收中";app.sampleTimes.push(now);while(app.sampleTimes[0]<now-1000)app.sampleTimes.shift();ui.sampleRate.textContent=app.sampleTimes.length+" Hz";const a=faceAngle(s);ui.liveAngle.textContent=fmt(a);ui.liveAngleHint.textContent=a===null?"等待重力数据":angleLabel(a);ui.peakHint.textContent="当前 "+fmt(s.totalG,2)+" g";app.chartSamples.push(s);while(app.chartSamples[0]?.t<now-3000)app.chartSamples.shift();if(app.active){app.samples.push(s);app.active.sampleCount++;app.active.maxG=Math.max(app.active.maxG,s.totalG)}if(app.calibrationRun)app.calibrationRun.samples.push(s);detect(s);updateChart()}
  window.onSensorData=(...v)=>ingest(v);
  function calibrate(kind,label){if(app.calibrationRun)return;const run={kind,label,samples:[]};app.calibrationRun=run;log(label+"校准开始，保持静止 2 秒");setTimeout(()=>{if(app.calibrationRun!==run)return;app.calibrationRun=null;const valid=run.samples.filter(s=>s.gravity);if(valid.length<30){log("校准失败：没有足够的新版重力数据");return}const gravity=[0,1,2].map(i=>valid.reduce((a,s)=>a+s.gravity[i],0)/valid.length);app.calibration[kind]={gravity,samples:valid.length,at:Date.now()};saveCal();if(kind==="back"&&app.calibration.front){const a=deg(Math.acos(clamp(dot(norm(app.calibration.front.gravity),norm(gravity)),-1,1)));log(label+"完成，正反面夹角 "+fmt(a)+"°")}else log(label+"校准完成")},2000)}
  function initChart(){if(!window.Chart)return;app.chart=new Chart(ui.motionChart,{type:"line",data:{labels:[],datasets:[{label:"冲击 g",data:[],borderColor:"#43df8a",pointRadius:0,borderWidth:2},{label:"角速度 rad/s",data:[],borderColor:"#67a8ff",pointRadius:0,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{labels:{color:"#96a2b2"}}},scales:{x:{ticks:{color:"#96a2b2"},grid:{color:"#202a36"}},y:{beginAtZero:true,ticks:{color:"#96a2b2"},grid:{color:"#202a36"}}}}})}
  function updateChart(){if(!app.chart)return;const n=app.chartSamples.at(-1)?.t||0;app.chart.data.labels=app.chartSamples.map(s=>((s.t-n)/1000).toFixed(1));app.chart.data.datasets[0].data=app.chartSamples.map(s=>s.totalG);app.chart.data.datasets[1].data=app.chartSamples.map(s=>s.rotNorm);app.chart.update("none")}
  function download(type){const s=app.active||app.sessions.find(x=>x.id===app.selected)||app.sessions[0];if(!s){log("没有可导出的 Session");return}let body,name;if(type==="json"){body=JSON.stringify({...s,calibration:app.calibration,rawSamples:app.active&&s.id===app.active.id?app.samples:undefined},null,2);name="airswing-"+s.id+".json"}else{const head="number,time,faceAngleDeg,targetDifferenceDeg,swingAngleDeg,stabilityDeg,peakG,peakRotationDegPerSec";body=[head,...s.hits.map(h=>[h.number,new Date(h.time).toISOString(),h.angle,h.angle-s.config.target,h.swingAngle,h.stability,h.peakG,h.peakRotDeg].join(","))].join("\n");name="airswing-"+s.id+".csv"}const u=URL.createObjectURL(new Blob([body],{type:type==="json"?"application/json":"text/csv"})),a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
  ui.startSession.onclick=startSession;ui.endSession.onclick=endSession;ui.exportJson.onclick=()=>download("json");ui.exportCsv.onclick=()=>download("csv");ui.calFront.onclick=()=>calibrate("front","正手面");ui.calBack.onclick=()=>calibrate("back","反面");ui.calVertical.onclick=()=>calibrate("vertical","竖直姿态");ui.clearCalibration.onclick=()=>{app.calibration={front:null,back:null,vertical:null};saveCal();log("校准已清除")};
  [["targetAngle","target"],["tolerance","tolerance"],["gThreshold","gThreshold"],["rotThreshold","rotThreshold"]].forEach(([id,key])=>ui[id].oninput=()=>{app.config[key]=Number(ui[id].value);saveConfig();renderConfig()});
  setInterval(()=>{if(app.lastAt&&performance.now()-app.lastAt>1300){ui.liveDot.classList.remove("live");ui.connectionText.textContent="等待 iPad 数据";ui.sampleRate.textContent="0 Hz"}},500);
  renderConfig();renderCalibration();renderSessions();initChart();log("角度训练版已就绪");
})();
