(() => {
  "use strict";
  const $=id=>document.getElementById(id), mag=(x,y,z)=>Math.hypot(x,y,z), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const norm=v=>{const m=Math.hypot(...v)||1;return v.map(n=>n/m)},dot=(a,b)=>a.reduce((s,n,i)=>s+n*b[i],0);
  const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
  const deg=r=>r*180/Math.PI, fmt=(v,d=1)=>Number.isFinite(v)?v.toFixed(d):"--";
  const KEYS={config:"airswing-angle-config-v1",cal:"airswing-angle-cal-v1",sessions:"airswing-sessions-v1"};
  const load=(k,f)=>{try{return{...f,...JSON.parse(localStorage.getItem(k)||"{}")}}catch{return f}};
  const ui={};["liveDot","connectionText","sampleRate","contactAngle","angleResult","sessionHitCount","sessionStatus","swingAngle","stability","peakRot","peakHint","liveAngle","liveAngleHint","horizontalFace","horizontalFaceHint","swingDirection","swingDirectionHint","readyDelta","readyDeltaHint","contactState","startSession","endSession","exportJson","exportCsv","protocolNotice","targetAngle","targetAngleValue","tolerance","toleranceValue","gThreshold","gThresholdValue","rotThreshold","rotThresholdValue","calZero","calFront","calBack","calVertical","calTable","calReady","zeroTag","frontTag","backTag","verticalTag","tableTag","readyTag","clearCalibration","eventLog","sessionList","hitTable","emptyHits","landingStatus","undoLanding","accelerationChart","rotationChart","angleChart"].forEach(id=>ui[id]=$(id));
  const app={
    config:load(KEYS.config,{target:-10,tolerance:8,gThreshold:2.2,rotThreshold:3.5}),
    calibration:load(KEYS.cal,{zero:null,front:null,back:null,vertical:null,table:null,ready:null}), sessions:[],
    active:null,selected:null,samples:[],chartSamples:[],sampleTimes:[],lastAt:0,chart:null,
    calibrationRun:null,stroke:null,preRoll:[],quietSince:0,lastStrokeAt:0,protocol:0,charts:[],quaternionMode:null
  };
  try{app.sessions=JSON.parse(localStorage.getItem(KEYS.sessions)||"[]")}catch{}
  const saveConfig=()=>localStorage.setItem(KEYS.config,JSON.stringify(app.config));
  const saveCal=()=>{localStorage.setItem(KEYS.cal,JSON.stringify(app.calibration));renderCalibration()};
  const saveSessions=()=>localStorage.setItem(KEYS.sessions,JSON.stringify(app.sessions.slice(0,30)));
  function log(text){const d=document.createElement("div");d.textContent=new Date().toLocaleTimeString()+"  "+text;ui.eventLog.prepend(d);while(ui.eventLog.children.length>18)ui.eventLog.lastChild.remove()}
  function angleLabel(v){if(!Number.isFinite(v))return"--";if(Math.abs(v)<1)return"接近竖直";return(v>0?"打开 ":"关闭 ")+Math.abs(Math.round(v))+"°"}
  function faceAxis(){const c=app.calibration.front;if(!c)return null;return norm(c.gravity.map(n=>-n))}
  function handleAxis(){const f=faceAxis(),c=app.calibration.vertical;if(!f||!c)return null;let h=norm(c.gravity.map(n=>-n));h=h.map((n,i)=>n-dot(h,f)*f[i]);return norm(h)}
  function faceAngle(s){const f=faceAxis();if(!f||!s.gravity)return null;return deg(Math.asin(clamp(dot(f,norm(s.gravity.map(n=>-n))),-1,1)))}
  function swingAngle(s){const h=handleAxis();if(!h||!s.gravity)return null;const v=cross([s.rotX,s.rotY,s.rotZ],h),up=norm(s.gravity.map(n=>-n));return deg(Math.atan2(dot(v,up),Math.hypot(...v.map((n,i)=>n-dot(v,up)*up[i]))))}
  function qConjugate(q){return[-q[0],-q[1],-q[2],q[3]]}
  function qRotate(q,v){const u=[q[0],q[1],q[2]],s=q[3],uv=cross(u,v),uuv=cross(u,uv);return v.map((n,i)=>n+2*s*uv[i]+2*uuv[i])}
  function worldVector(v,q,gravity){if(!q)return null;if(!app.quaternionMode&&gravity){const target=[0,0,-1],direct=qRotate(q,gravity),inverse=qRotate(qConjugate(q),gravity),error=a=>a.reduce((sum,n,i)=>sum+(n-target[i])**2,0);app.quaternionMode=error(direct)<=error(inverse)?"direct":"inverse"}return qRotate(app.quaternionMode==="inverse"?qConjugate(q):q,v)}
  function tableBasis(){const f=faceAxis(),h=handleAxis(),t=app.calibration.table,v=app.calibration.vertical;if(!f||!v?.quaternion)return null;const forwardRaw=t?.quaternion&&h?worldVector(h,t.quaternion,t.gravity):worldVector(f,v.quaternion,v.gravity);if(!forwardRaw)return null;const up=[0,0,1],flat=forwardRaw.map((n,i)=>n-dot(forwardRaw,up)*up[i]);if(Math.hypot(...flat)<.05)return null;const forward=norm(flat);return{up,forward,right:norm(cross(forward,up))}}
  function horizontalMetrics(s){const basis=tableBasis(),f=faceAxis(),h=handleAxis();if(!basis||!f||!h||!s.quaternion)return{faceYaw:null,swingYaw:null};const faceWorld=worldVector(f,s.quaternion,s.gravity),faceFlat=faceWorld.map((n,i)=>n-dot(faceWorld,basis.up)*basis.up[i]),omegaWorld=worldVector([s.rotX,s.rotY,s.rotZ],s.quaternion,s.gravity),headWorld=worldVector(h,s.quaternion,s.gravity),velocity=cross(omegaWorld,headWorld),velocityFlat=velocity.map((n,i)=>n-dot(velocity,basis.up)*basis.up[i]),faceHorizontal=Math.hypot(...faceFlat)>.05?norm(faceFlat):null,velocityHorizontal=Math.hypot(...velocityFlat)>.01?norm(velocityFlat):null;return{faceYaw:faceHorizontal?deg(Math.atan2(dot(faceHorizontal,basis.right),dot(faceHorizontal,basis.forward))):null,swingYaw:velocityHorizontal?deg(Math.atan2(dot(velocityHorizontal,basis.right),dot(velocityHorizontal,basis.forward))):null}}
  function directionLabel(v){if(!Number.isFinite(v))return"需要重新校准竖直姿态";if(Math.abs(v)<2)return"接近正前方";return(v>0?"向右 ":"向左 ")+fmt(Math.abs(v))+"°"}
  function orientationDelta(s){const ready=app.calibration.ready?.quaternion;if(!ready||!s.quaternion)return null;return deg(2*Math.acos(clamp(Math.abs(dot(norm(ready),norm(s.quaternion))),-1,1)))}
  function renderCalibration(){ui.zeroTag.classList.toggle("ready",!!app.calibration.zero);ui.frontTag.classList.toggle("ready",!!app.calibration.front);ui.backTag.classList.toggle("ready",!!app.calibration.back);ui.verticalTag.classList.toggle("ready",!!app.calibration.vertical?.quaternion);ui.tableTag.classList.toggle("ready",!!app.calibration.table?.quaternion);ui.readyTag.classList.toggle("ready",!!app.calibration.ready?.quaternion)}
  function renderConfig(){ui.targetAngle.value=app.config.target;ui.tolerance.value=app.config.tolerance;ui.gThreshold.value=app.config.gThreshold;ui.rotThreshold.value=app.config.rotThreshold;ui.targetAngleValue.textContent=angleLabel(app.config.target);ui.toleranceValue.textContent=app.config.tolerance;ui.gThresholdValue.textContent=Number(app.config.gThreshold).toFixed(1);ui.rotThresholdValue.textContent=Number(app.config.rotThreshold).toFixed(1)}
  function selectedSession(){const list=app.active?[app.active,...app.sessions]:app.sessions;return list.find(s=>s.id===app.selected)||app.active||app.sessions[0]}
  function renderSessions(){ui.sessionList.innerHTML="";const list=app.active?[app.active,...app.sessions]:app.sessions;if(!list.length){ui.sessionList.innerHTML='<div class="empty">还没有 Session</div>'}list.forEach(s=>{const b=document.createElement("button"),marked=s.hits.filter(h=>h.landing).length;b.className="session-item"+(app.selected===s.id?" active":"");b.innerHTML="<strong>"+(s.active?"训练中":"Session")+" · "+s.hits.length+" 次</strong><span>已标记 "+marked+" · "+new Date(s.startedAt).toLocaleString()+"</span>";b.onclick=()=>{app.selected=s.id;renderSessions()};ui.sessionList.appendChild(b)});const shown=selectedSession();renderHits(shown);renderLandingStatus(shown)}
  function renderHits(s){ui.hitTable.innerHTML="";ui.emptyHits.style.display=s&&s.hits.length?"none":"block";if(!s)return;s.hits.forEach(h=>{const tr=document.createElement("tr"),diff=h.angle-app.config.target;tr.innerHTML="<td>#"+h.number+"</td><td>"+(h.landing?.label||"未标记")+"</td><td>"+new Date(h.time).toLocaleTimeString()+"</td><td>"+angleLabel(h.angle)+"</td><td>"+(Number.isFinite(h.faceYaw)?directionLabel(h.faceYaw):"--")+"</td><td>"+(Number.isFinite(h.swingYaw)?directionLabel(h.swingYaw):"--")+"</td><td>"+fmt(h.readyDelta)+"°</td><td>"+(diff>=0?"+":"")+fmt(diff)+"°</td><td>"+fmt(h.swingAngle)+"°</td><td>"+fmt(h.stability)+"°</td><td>"+fmt(h.peakG,2)+"</td><td>"+Math.round(h.peakRotDeg)+"°/s</td>";ui.hitTable.appendChild(tr)})}
  function renderLandingStatus(s){if(!s||!s.hits.length){ui.landingStatus.textContent="等待 Session 击球";return}const pending=[...s.hits].reverse().find(h=>!h.landing);ui.landingStatus.textContent=pending?"待标记：击球 #"+pending.number:"本 Session 已全部标记"}
  const landingLabels={"far-left":"左远","far-center":"中远","far-right":"右远","mid-left":"左中","mid-center":"中间","mid-right":"右中","near-left":"左近","near-center":"中近","near-right":"右近",net:"下网","out-long":"远出界","out-left":"左出界","out-right":"右出界"};
  function landingData(code){if(code==="net")return{outcome:"net",depth:"short",lateral:"center"};if(code==="out-long")return{outcome:"out",depth:"long",lateral:"center"};if(code==="out-left")return{outcome:"out",depth:"unknown",lateral:"left"};if(code==="out-right")return{outcome:"out",depth:"unknown",lateral:"right"};const [depth,lateral]=code.split("-");return{outcome:"in",depth,lateral}}
  function markLanding(code){const s=selectedSession();if(!s||!s.hits.length){log("还没有可标记的击球");return}const hit=[...s.hits].reverse().find(h=>!h.landing);if(!hit){log("当前 Session 已全部标记");return}hit.landing={code,label:landingLabels[code],...landingData(code),markedAt:Date.now()};if(!s.active)saveSessions();log("击球 #"+hit.number+" 标记为 "+hit.landing.label);renderSessions()}
  function undoLanding(){const s=selectedSession();if(!s)return;const hit=[...s.hits].reverse().find(h=>h.landing);if(!hit){log("没有可撤销的落点标记");return}const label=hit.landing.label;delete hit.landing;if(!s.active)saveSessions();log("已撤销击球 #"+hit.number+" 的 "+label);renderSessions()}
  function startSession(){if(app.active)return;app.active={id:"s-"+Date.now(),startedAt:Date.now(),endedAt:null,active:true,hits:[],sampleCount:0,maxG:0,config:{...app.config}};app.samples=[];app.selected=app.active.id;ui.startSession.disabled=true;ui.endSession.disabled=false;ui.sessionStatus.textContent="训练进行中";ui.sessionHitCount.textContent="0";log("Session 已开始");renderSessions()}
  function endSession(){if(!app.active)return;app.active.active=false;app.active.endedAt=Date.now();app.sessions.unshift(app.active);app.sessions=app.sessions.slice(0,30);app.selected=app.active.id;app.active=null;saveSessions();ui.startSession.disabled=false;ui.endSession.disabled=true;ui.sessionStatus.textContent="已保存，可在下方回看";log("Session 已结束并保存");renderSessions()}
  function feedback(h){ui.contactAngle.textContent=fmt(h.angle);ui.swingAngle.textContent=fmt(h.swingAngle);ui.stability.textContent=fmt(h.stability);ui.horizontalFace.textContent=fmt(h.faceYaw);ui.horizontalFaceHint.textContent=directionLabel(h.faceYaw);ui.swingDirection.textContent=fmt(h.swingYaw);ui.swingDirectionHint.textContent=directionLabel(h.swingYaw)+" · 旋转分量";ui.readyDelta.textContent=fmt(h.readyDelta);ui.readyDeltaHint.textContent=Number.isFinite(h.readyDelta)?"相对个人准备姿态":"需要准备姿态校准";ui.peakRot.textContent=Math.round(h.peakRotDeg);ui.peakHint.textContent="峰值 "+fmt(h.peakG,2)+" g";ui.contactState.textContent="已记录";const d=h.angle-app.config.target,a=Math.abs(d),cls=a<=app.config.tolerance?"good":a<=app.config.tolerance*2?"warn":"bad";ui.angleResult.className="hint "+cls;ui.angleResult.textContent=angleLabel(h.angle)+" · "+(a<.5?"达到目标":(d>0?"比目标更打开 ":"比目标更关闭 ")+fmt(a)+"°");document.body.classList.remove("flash");void document.body.offsetWidth;document.body.classList.add("flash")}
  function finishStroke(){const st=app.stroke;app.stroke=null;app.quietSince=0;if(!st||st.length<5)return;let peak=st[0],score=-1;st.forEach(s=>{const q=s.totalG/app.config.gThreshold+s.rotNorm/app.config.rotThreshold;if(q>score){score=q;peak=s}});app.lastStrokeAt=st.at(-1).t;if(peak.totalG<app.config.gThreshold||peak.rotNorm<app.config.rotThreshold)return;const wanted=peak.t-40,contact=st.reduce((best,s)=>s.t<=peak.t&&Math.abs(s.t-wanted)<Math.abs(best.t-wanted)?s:best,peak);const angle=faceAngle(contact);if(angle===null){log("检测到击球，但旧版网桥没有重力数据");return}const horizontal=horizontalMetrics(contact),pre=st.filter(s=>s.t>=contact.t-140&&s.t<=contact.t).map(faceAngle).filter(Number.isFinite),mean=pre.reduce((a,b)=>a+b,0)/(pre.length||1),stability=Math.sqrt(pre.reduce((a,b)=>a+(b-mean)**2,0)/(pre.length||1));const h={number:app.active?app.active.hits.length+1:0,time:peak.wallTime,angle,faceYaw:horizontal.faceYaw,swingYaw:horizontal.swingYaw,readyDelta:orientationDelta(contact),swingAngle:swingAngle(contact),stability,peakG:Math.max(...st.map(s=>s.totalG)),peakRotDeg:deg(Math.max(...st.map(s=>s.rotNorm))),contactOffsetMs:-40};feedback(h);if(app.active){app.active.hits.push(h);ui.sessionHitCount.textContent=app.active.hits.length;renderSessions();log("记录击球 #"+h.number+"，"+angleLabel(angle))}else log("检测到击球；开始 Session 后才会保存")}
  function detect(s){app.preRoll.push(s);while(app.preRoll.length>8)app.preRoll.shift();if(!app.stroke){if(s.rotNorm>1.8&&s.t-app.lastStrokeAt>180)app.stroke=app.preRoll.slice();return}app.stroke.push(s);if(s.rotNorm<.8){if(!app.quietSince)app.quietSince=s.t;if(s.t-app.quietSince>120)finishStroke()}else app.quietSince=0;if(app.stroke&&s.t-app.stroke[0].t>1500)finishStroke()}
  function ingest(values,source="ipad"){const [ax,ay,az,rx,ry,rz,gx,gy,gz,qx,qy,qz,qw]=values.map(Number),now=performance.now();if(![ax,ay,az,rx,ry,rz].every(Number.isFinite))return;const rawAcc=[ax,ay,az],rawRot=[rx,ry,rz],accBias=app.calibration.zero?.accBias||[0,0,0],rotBias=app.calibration.zero?.rotBias||[0,0,0],acc=rawAcc.map((n,i)=>n-(accBias[i]||0)),rot=rawRot.map((n,i)=>n-(rotBias[i]||0));const s={t:now,wallTime:Date.now(),source,rawAcc,rawRot,accX:acc[0],accY:acc[1],accZ:acc[2],rotX:rot[0],rotY:rot[1],rotZ:rot[2],totalG:mag(...acc),rotNorm:mag(...rot),gravity:[gx,gy,gz].every(Number.isFinite)?[gx,gy,gz]:null,quaternion:[qx,qy,qz,qw].every(Number.isFinite)?[qx,qy,qz,qw]:null};app.lastAt=now;app.protocol=s.gravity?2:1;ui.protocolNotice.textContent=s.gravity?"13 项数据已连接，拍面角可用":"只收到 "+values.length+" 项数据：当前运行的是旧 Swift 项目";ui.protocolNotice.className=s.gravity?"protocol good":"protocol";ui.liveDot.classList.add("live");ui.connectionText.textContent="接收中";app.sampleTimes.push(now);while(app.sampleTimes[0]<now-1000)app.sampleTimes.shift();ui.sampleRate.textContent=app.sampleTimes.length+" Hz";const a=faceAngle(s);ui.liveAngle.textContent=fmt(a);ui.liveAngleHint.textContent=a===null?"等待重力数据":angleLabel(a);ui.peakHint.textContent="当前 "+fmt(s.totalG,2)+" g";app.chartSamples.push(s);while(app.chartSamples[0]?.t<now-3000)app.chartSamples.shift();if(app.active){app.samples.push(s);app.active.sampleCount++;app.active.maxG=Math.max(app.active.maxG,s.totalG)}if(app.calibrationRun)app.calibrationRun.samples.push(s);detect(s);updateChart()}
  window.onSensorData=(...v)=>ingest(v);
  function calibrate(kind,label){if(app.calibrationRun)return;if(kind==="table"&&(!faceAxis()||!handleAxis())){log("请先完成正面和竖直校准");return}const duration=kind==="zero"?3000:2000,run={kind,label,samples:[]};app.calibrationRun=run;log(label+"校准开始，保持静止 "+duration/1000+" 秒");setTimeout(()=>{if(app.calibrationRun!==run)return;app.calibrationRun=null;const valid=run.samples.filter(s=>s.gravity&&s.quaternion);if(valid.length<(kind==="zero"?45:30)){log("校准失败：没有足够的姿态数据");return}const gravity=[0,1,2].map(i=>valid.reduce((a,s)=>a+s.gravity[i],0)/valid.length),reference=valid[0].quaternion,qsum=[0,0,0,0];valid.forEach(s=>{const sign=dot(s.quaternion,reference)<0?-1:1;s.quaternion.forEach((n,i)=>qsum[i]+=n*sign)});const quaternion=norm(qsum),base={gravity,quaternion,samples:valid.length,at:Date.now()};if(kind==="zero"){const rotBias=[0,1,2].map(i=>valid.reduce((a,s)=>a+s.rawRot[i],0)/valid.length),linear=valid.map(s=>s.rawAcc.map((n,i)=>n-s.gravity[i])),accBias=[0,1,2].map(i=>linear.reduce((a,v)=>a+v[i],0)/linear.length),rotNoise=Math.sqrt(valid.reduce((a,s)=>a+s.rawRot.reduce((q,n,i)=>q+(n-rotBias[i])**2,0),0)/valid.length),accNoise=Math.sqrt(linear.reduce((a,v)=>a+v.reduce((q,n,i)=>q+(n-accBias[i])**2,0),0)/linear.length);app.calibration.zero={...base,rotBias,accBias,rotNoise,accNoise};log(label+"完成，陀螺噪声 "+fmt(deg(rotNoise),2)+"°/s，加速度噪声 "+fmt(accNoise,3)+" g")}else{app.calibration[kind]=base;if(kind==="vertical"||kind==="table")app.quaternionMode=null;if(kind==="back"&&app.calibration.front){const a=deg(Math.acos(clamp(dot(norm(app.calibration.front.gravity),norm(gravity)),-1,1)));log(label+"完成，正反面夹角 "+fmt(a)+"°")}else log(label+"校准完成")}saveCal()},duration)}
  function drawSeries(chart){const c=chart.canvas,ctx=c.getContext("2d"),dpr=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;if(!w||!h)return;if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const data=app.chartSamples,values=data.map(chart.value).filter(Number.isFinite),pad={l:40,r:10,t:10,b:22},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b;let min=chart.symmetric?-Math.max(chart.floor,...values.map(Math.abs)):0,max=chart.symmetric?Math.max(chart.floor,...values.map(Math.abs)):Math.max(chart.floor,...values);if(chart.symmetric)max=-min;ctx.strokeStyle="#202a36";ctx.fillStyle="#96a2b2";ctx.font="11px system-ui";for(let i=0;i<=4;i++){const y=pad.t+ph*i/4,v=max-(max-min)*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText(fmt(v,0),4,y+4)}if(values.length>1){ctx.strokeStyle=chart.color;ctx.lineWidth=2;ctx.beginPath();values.forEach((v,i)=>{const x=pad.l+pw*i/(values.length-1),y=pad.t+ph*(max-v)/(max-min);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}ctx.fillStyle="#96a2b2";ctx.fillText("-3s",pad.l,h-4);ctx.fillText("现在",w-pad.r-24,h-4)}
  function drawCharts(){app.charts.forEach(drawSeries)}
  function initChart(){app.charts=[{canvas:ui.accelerationChart,value:s=>s.totalG,color:"#43df8a",floor:4,symmetric:false},{canvas:ui.rotationChart,value:s=>deg(s.rotNorm),color:"#67a8ff",floor:720,symmetric:false},{canvas:ui.angleChart,value:s=>faceAngle(s),color:"#f4c95d",floor:45,symmetric:true}];window.addEventListener("resize",drawCharts);drawCharts()}
  function updateChart(){drawCharts()}
  function download(type){const s=app.active||app.sessions.find(x=>x.id===app.selected)||app.sessions[0];if(!s){log("没有可导出的 Session");return}let body,name;if(type==="json"){body=JSON.stringify({...s,calibration:app.calibration,rawSamples:app.active&&s.id===app.active.id?app.samples:undefined},null,2);name="airswing-"+s.id+".json"}else{const head="number,landingCode,landingLabel,outcome,depth,lateral,time,faceAngleDeg,faceYawDeg,swingYawDeg,readyDeltaDeg,targetDifferenceDeg,swingAngleDeg,stabilityDeg,peakG,peakRotationDegPerSec";body=[head,...s.hits.map(h=>[h.number,h.landing?.code||"",h.landing?.label||"",h.landing?.outcome||"",h.landing?.depth||"",h.landing?.lateral||"",new Date(h.time).toISOString(),h.angle,h.faceYaw,h.swingYaw,h.readyDelta,h.angle-s.config.target,h.swingAngle,h.stability,h.peakG,h.peakRotDeg].join(","))].join("\n");name="airswing-"+s.id+".csv"}const u=URL.createObjectURL(new Blob([body],{type:type==="json"?"application/json":"text/csv"})),a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
  ui.startSession.onclick=startSession;ui.endSession.onclick=endSession;ui.exportJson.onclick=()=>download("json");ui.exportCsv.onclick=()=>download("csv");ui.undoLanding.onclick=undoLanding;document.querySelectorAll("[data-landing]").forEach(button=>button.onclick=()=>markLanding(button.dataset.landing));ui.calZero.onclick=()=>calibrate("zero","静止零偏");ui.calFront.onclick=()=>calibrate("front","正手面");ui.calBack.onclick=()=>calibrate("back","反面");ui.calVertical.onclick=()=>calibrate("vertical","竖直姿态");ui.calTable.onclick=()=>calibrate("table","球桌方向");ui.calReady.onclick=()=>calibrate("ready","准备姿态");ui.clearCalibration.onclick=()=>{app.calibration={zero:null,front:null,back:null,vertical:null,table:null,ready:null};app.quaternionMode=null;saveCal();log("校准已清除")};
  [["targetAngle","target"],["tolerance","tolerance"],["gThreshold","gThreshold"],["rotThreshold","rotThreshold"]].forEach(([id,key])=>ui[id].oninput=()=>{app.config[key]=Number(ui[id].value);saveConfig();renderConfig()});
  setInterval(()=>{if(app.lastAt&&performance.now()-app.lastAt>1300){ui.liveDot.classList.remove("live");ui.connectionText.textContent="等待 iPad 数据";ui.sampleRate.textContent="0 Hz"}},500);
  renderConfig();renderCalibration();renderSessions();initChart();log("角度训练版已就绪");
})();
